mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod "property_list_key", "0.1.0",  :github_tarball => "glarizza/puppet-property_list_key"
